version: "3"

services:
  front:
    build: site-e-commerce
    ports:
      - "80:80"

  api:
    build: api
    tty: true
    stdin_open: true
    depends_on:
      - db
      - adminer
    ports:
      - "3000:3000"

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080
